const ALLOWED_KEYWORDS: readonly string[] = [
  "boitenluhrs",
  "dienst",
  "product",
  "prijs",
  "contact",
  "betaling",
  "betalen",
  "betaald",
  "factuur",
  "openingstijd",
  "adres",
  "schuld",
  "lening",
  "aflossing",
  "achterstand",
  "incasso",
  "betalingsregeling",
  "budget",
  "vordering",
  "deurwaarder",
  "debiteur",
  "beslag",
  "herinnering",
  "openstaand",
  "kenmerk",
  "oplichter",
  "legitiem",
  "niet betalen",
  "telefoon",
  "telefoonnummer",
  "bellen",
  "nummer",
  "bereikbaar",
  "mail",
  "email",
  "e-mail",
  "locatie",
  "vestiging",
  "kantoor",
];

export function isRelevant(message: string): boolean {
  const lower = message.toLowerCase();
  return ALLOWED_KEYWORDS.some((keyword) => lower.includes(keyword));
}
